ALTER TABLE factures ADD COLUMN IF NOT EXISTS montant_ht numeric DEFAULT 0;
ALTER TABLE factures ADD COLUMN IF NOT EXISTS tva numeric DEFAULT 0;
ALTER TABLE factures ADD COLUMN IF NOT EXISTS taxes numeric DEFAULT 0;
