-- Seed: Provinces, Localisations & Chantiers
-- Généré à partir de Liste_Projets_LRC_par_Province.csv
-- À exécuter APRÈS la migration

-- 1. Provinces
INSERT INTO zones_geographiques (nom) VALUES ('ESTUAIRE') ON CONFLICT (nom) DO NOTHING;
INSERT INTO zones_geographiques (nom) VALUES ('HAUT OGOOUE') ON CONFLICT (nom) DO NOTHING;
INSERT INTO zones_geographiques (nom) VALUES ('NGOUNIE') ON CONFLICT (nom) DO NOTHING;
INSERT INTO zones_geographiques (nom) VALUES ('OGOOUE IVINDO') ON CONFLICT (nom) DO NOTHING;
INSERT INTO zones_geographiques (nom) VALUES ('OGOOUE LOLO') ON CONFLICT (nom) DO NOTHING;
INSERT INTO zones_geographiques (nom) VALUES ('OGOOUE MARITIME') ON CONFLICT (nom) DO NOTHING;
INSERT INTO zones_geographiques (nom) VALUES ('WOLEU NTEM') ON CONFLICT (nom) DO NOTHING;

-- 2. Localisations
WITH zone_ids AS (SELECT id, nom FROM zones_geographiques)
INSERT INTO localisations (nom, zone_id)
VALUES
  ('MBOUMA', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE MARITIME')),
  ('FRANCEVILLE', (SELECT id FROM zone_ids WHERE nom = 'HAUT OGOOUE')),
  ('BITAM', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('OKONDJA', (SELECT id FROM zone_ids WHERE nom = 'HAUT OGOOUE')),
  ('MEDOUNEU', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('CUSS', (SELECT id FROM zone_ids WHERE nom = 'ESTUAIRE')),
  ('INSG', (SELECT id FROM zone_ids WHERE nom = 'ESTUAIRE')),
  ('MINVOUL', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('MAKONGONIO', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE')),
  ('NDENDE', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE')),
  ('LASTOURSVILLE', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE LOLO')),
  ('AVORBAM', (SELECT id FROM zone_ids WHERE nom = 'ESTUAIRE')),
  ('MALINGA', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE')),
  ('MITZIC', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('MINDOUBE 2', (SELECT id FROM zone_ids WHERE nom = 'ESTUAIRE')),
  ('LEBAMBA-MAKONGOGNIO-MBIGOU', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE')),
  ('GUIETSOU', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE')),
  ('OYEM', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('OMBOUE', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE MARITIME')),
  ('OYEM - OLIGUI VILLE', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('ASSOCK NGOMO', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('KOULAMOUTOU', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE LOLO')),
  ('MAKOKOU-MEKAMBO-EKATA', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE IVINDO')),
  ('PK0-PK5', (SELECT id FROM zone_ids WHERE nom = 'ESTUAIRE')),
  ('MAKOKOU', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE IVINDO')),
  ('NZENZELE', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE')),
  ('MEKAMBO', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE IVINDO')),
  ('MBOUMA-AKONDO', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE MARITIME')),
  ('ALEMBE - LOPE - LASTOURVILLE', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE IVINDO')),
  ('KANGO', (SELECT id FROM zone_ids WHERE nom = 'ESTUAIRE')),
  ('MOUILA', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE')),
  ('PORT GENTIL', (SELECT id FROM zone_ids WHERE nom = 'OGOOUE MARITIME')),
  ('MOUILA - MIMONGO', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE')),
  ('LALARA', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('NTOUM', (SELECT id FROM zone_ids WHERE nom = 'ESTUAIRE')),
  ('UOB', (SELECT id FROM zone_ids WHERE nom = 'ESTUAIRE')),
  ('MANDJI', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE')),
  ('NKOUM YENGUIN', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('OYEM-MINVOUL', (SELECT id FROM zone_ids WHERE nom = 'WOLEU NTEM')),
  ('MBIGOU', (SELECT id FROM zone_ids WHERE nom = 'NGOUNIE'));

-- 3. Chantiers
WITH loc_ids AS (SELECT l.id, l.nom AS loc_nom, z.nom AS zone_nom FROM localisations l JOIN zones_geographiques z ON z.id = l.zone_id)
INSERT INTO chantiers (nom, code, localisation_id)
VALUES
  ('VOIRIES DE NTOUM (15KM)', 'CH-001', (SELECT id FROM loc_ids WHERE loc_nom = 'NTOUM' AND zone_nom = 'ESTUAIRE')),
  ('COMPLEXE MULTISPORTIF', 'CH-002', (SELECT id FROM loc_ids WHERE loc_nom = 'NTOUM' AND zone_nom = 'ESTUAIRE')),
  ('STATION GAB''OIL', 'CH-003', (SELECT id FROM loc_ids WHERE loc_nom = 'NTOUM' AND zone_nom = 'ESTUAIRE')),
  ('STATION GAB''OIL', 'CH-004', (SELECT id FROM loc_ids WHERE loc_nom = 'AVORBAM' AND zone_nom = 'ESTUAIRE')),
  ('STATION GAB''OIL', 'CH-005', (SELECT id FROM loc_ids WHERE loc_nom = 'MINDOUBE 2' AND zone_nom = 'ESTUAIRE')),
  ('STATION GAB''OIL', 'CH-006', (SELECT id FROM loc_ids WHERE loc_nom = 'KANGO' AND zone_nom = 'ESTUAIRE')),
  ('VOIRIE UOB (1,425 KM)', 'CH-007', (SELECT id FROM loc_ids WHERE loc_nom = 'UOB' AND zone_nom = 'ESTUAIRE')),
  ('VOIRIE CUSS (1,05 KM)', 'CH-008', (SELECT id FROM loc_ids WHERE loc_nom = 'CUSS' AND zone_nom = 'ESTUAIRE')),
  ('VOIRIE INSG(0,277 KM)', 'CH-009', (SELECT id FROM loc_ids WHERE loc_nom = 'INSG' AND zone_nom = 'ESTUAIRE')),
  ('Aménagement de la ville de Libreville', 'CH-010', (SELECT id FROM loc_ids WHERE loc_nom = 'PK0-PK5' AND zone_nom = 'ESTUAIRE')),
  ('VOIRIES BETONNEES DE OYEM  (30,13 KM)', 'CH-011', (SELECT id FROM loc_ids WHERE loc_nom = 'OYEM' AND zone_nom = 'WOLEU NTEM')),
  ('VOIRIES D''OYEM (8 KM) EN BETON BITUMINEUX', 'CH-012', (SELECT id FROM loc_ids WHERE loc_nom = 'OYEM' AND zone_nom = 'WOLEU NTEM')),
  ('LOGEMENTS RADIO 9', 'CH-013', (SELECT id FROM loc_ids WHERE loc_nom = 'OYEM' AND zone_nom = 'WOLEU NTEM')),
  ('AMENAGEMENT DE OLIGUI VILLE', 'CH-014', (SELECT id FROM loc_ids WHERE loc_nom = 'OYEM - OLIGUI VILLE' AND zone_nom = 'WOLEU NTEM')),
  ('PARC D''ATTRACTION', 'CH-015', (SELECT id FROM loc_ids WHERE loc_nom = 'OYEM - OLIGUI VILLE' AND zone_nom = 'WOLEU NTEM')),
  ('NKOUM YENGUIN VOIRIE (10km)', 'CH-016', (SELECT id FROM loc_ids WHERE loc_nom = 'NKOUM YENGUIN' AND zone_nom = 'WOLEU NTEM')),
  ('STATION SERVICE COMMUNAUTAIRE', 'CH-017', (SELECT id FROM loc_ids WHERE loc_nom = 'NKOUM YENGUIN' AND zone_nom = 'WOLEU NTEM')),
  ('PARKING EGLISE', 'CH-018', (SELECT id FROM loc_ids WHERE loc_nom = 'NKOUM YENGUIN' AND zone_nom = 'WOLEU NTEM')),
  ('MAIRIE DE NKOUM', 'CH-019', (SELECT id FROM loc_ids WHERE loc_nom = 'NKOUM YENGUIN' AND zone_nom = 'WOLEU NTEM')),
  ('SOUS-PREFECTURE DE NKOUM YEGUIN', 'CH-020', (SELECT id FROM loc_ids WHERE loc_nom = 'NKOUM YENGUIN' AND zone_nom = 'WOLEU NTEM')),
  ('GENDARMERIE', 'CH-021', (SELECT id FROM loc_ids WHERE loc_nom = 'NKOUM YENGUIN' AND zone_nom = 'WOLEU NTEM')),
  ('PLACE DE L''INDEPENDANCE', 'CH-022', (SELECT id FROM loc_ids WHERE loc_nom = 'NKOUM YENGUIN' AND zone_nom = 'WOLEU NTEM')),
  ('FERME', 'CH-023', (SELECT id FROM loc_ids WHERE loc_nom = 'NKOUM YENGUIN' AND zone_nom = 'WOLEU NTEM')),
  ('STATION GAB''OIL', 'CH-024', (SELECT id FROM loc_ids WHERE loc_nom = 'ASSOCK NGOMO' AND zone_nom = 'WOLEU NTEM')),
  ('ASSOK NGOMO-MINVOUL-KOM(120km)', 'CH-025', (SELECT id FROM loc_ids WHERE loc_nom = 'OYEM-MINVOUL' AND zone_nom = 'WOLEU NTEM')),
  ('VOIRIES DE MINVOUL (20 km)', 'CH-026', (SELECT id FROM loc_ids WHERE loc_nom = 'MINVOUL' AND zone_nom = 'WOLEU NTEM')),
  ('PLATEAU MULTI SPORTIF', 'CH-027', (SELECT id FROM loc_ids WHERE loc_nom = 'MINVOUL' AND zone_nom = 'WOLEU NTEM')),
  ('STATION GAB''OIL', 'CH-028', (SELECT id FROM loc_ids WHERE loc_nom = 'MINVOUL' AND zone_nom = 'WOLEU NTEM')),
  ('NKOLOMENGOUA-BIKODOME-EBOMANE (100km)', 'CH-029', (SELECT id FROM loc_ids WHERE loc_nom = 'BITAM' AND zone_nom = 'WOLEU NTEM')),
  ('NKOLOMENGOUA BIDOUMSSANG (100km)', 'CH-030', (SELECT id FROM loc_ids WHERE loc_nom = 'BITAM' AND zone_nom = 'WOLEU NTEM')),
  ('BIDOUMSSANG - ALENE - AKAM (25km)', 'CH-031', (SELECT id FROM loc_ids WHERE loc_nom = 'BITAM' AND zone_nom = 'WOLEU NTEM')),
  ('VOIRIES DE BITAM (20km)', 'CH-032', (SELECT id FROM loc_ids WHERE loc_nom = 'BITAM' AND zone_nom = 'WOLEU NTEM')),
  ('ROUTE DE MEYO-KYE-EBORO (25 KM)', 'CH-033', (SELECT id FROM loc_ids WHERE loc_nom = 'BITAM' AND zone_nom = 'WOLEU NTEM')),
  ('VOIRIE DE MEDOUNEU (10KM)', 'CH-034', (SELECT id FROM loc_ids WHERE loc_nom = 'MEDOUNEU' AND zone_nom = 'WOLEU NTEM')),
  ('STATION GAB''OIL', 'CH-035', (SELECT id FROM loc_ids WHERE loc_nom = 'MEDOUNEU' AND zone_nom = 'WOLEU NTEM')),
  ('VOIRIE DE MITZIC', 'CH-036', (SELECT id FROM loc_ids WHERE loc_nom = 'MITZIC' AND zone_nom = 'WOLEU NTEM')),
  ('STATION GAB''OIL', 'CH-037', (SELECT id FROM loc_ids WHERE loc_nom = 'LALARA' AND zone_nom = 'WOLEU NTEM')),
  ('CONSTRUCTION DE L''UNIVERSITE', 'CH-038', (SELECT id FROM loc_ids WHERE loc_nom = 'MOUILA' AND zone_nom = 'NGOUNIE')),
  ('STATION GAB''OIL', 'CH-039', (SELECT id FROM loc_ids WHERE loc_nom = 'MOUILA' AND zone_nom = 'NGOUNIE')),
  ('VOIRIE ET VOIE D''ACCES UNIVERSITE MOUILA', 'CH-040', (SELECT id FROM loc_ids WHERE loc_nom = 'MOUILA' AND zone_nom = 'NGOUNIE')),
  ('ROUTE MOUILA-MIMONGO (92KM)', 'CH-041', (SELECT id FROM loc_ids WHERE loc_nom = 'MOUILA - MIMONGO' AND zone_nom = 'NGOUNIE')),
  ('VOIRIES DE NDENDE (12 KM)', 'CH-042', (SELECT id FROM loc_ids WHERE loc_nom = 'NDENDE' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENTS SOCIAUX (30 logements)', 'CH-043', (SELECT id FROM loc_ids WHERE loc_nom = 'NDENDE' AND zone_nom = 'NGOUNIE')),
  ('VOIRIES MANDJI (21 KM)', 'CH-044', (SELECT id FROM loc_ids WHERE loc_nom = 'MANDJI' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION DU CENTRE  DE  SANTE DE MANDJI', 'CH-045', (SELECT id FROM loc_ids WHERE loc_nom = 'MANDJI' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENTS SOCIAUX (40 logements)', 'CH-046', (SELECT id FROM loc_ids WHERE loc_nom = 'MANDJI' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENTS D''ASTREINTS', 'CH-047', (SELECT id FROM loc_ids WHERE loc_nom = 'MANDJI' AND zone_nom = 'NGOUNIE')),
  ('PLATEAU MULTI SPORTIF', 'CH-048', (SELECT id FROM loc_ids WHERE loc_nom = 'MANDJI' AND zone_nom = 'NGOUNIE')),
  ('TERRAIN DE FOOTBALL', 'CH-049', (SELECT id FROM loc_ids WHERE loc_nom = 'MANDJI' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION D''UNE TRIBUNE OFFICIELLE', 'CH-050', (SELECT id FROM loc_ids WHERE loc_nom = 'MANDJI' AND zone_nom = 'NGOUNIE')),
  ('STATION GAB''OIL', 'CH-051', (SELECT id FROM loc_ids WHERE loc_nom = 'MANDJI' AND zone_nom = 'NGOUNIE')),
  ('VOIRIES DE MALINGA (8 KM)', 'CH-052', (SELECT id FROM loc_ids WHERE loc_nom = 'MALINGA' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION D''UN CENTRE DE SANTE DE MALINGA', 'CH-053', (SELECT id FROM loc_ids WHERE loc_nom = 'MALINGA' AND zone_nom = 'NGOUNIE')),
  ('REHABILITATION DU TRESOR PUBLIC', 'CH-054', (SELECT id FROM loc_ids WHERE loc_nom = 'MALINGA' AND zone_nom = 'NGOUNIE')),
  ('REHABILITATION PLACE DE FETE', 'CH-055', (SELECT id FROM loc_ids WHERE loc_nom = 'MALINGA' AND zone_nom = 'NGOUNIE')),
  ('REHABILITATION MAIRIE', 'CH-056', (SELECT id FROM loc_ids WHERE loc_nom = 'MALINGA' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENTS SOCIAUX (30 logements)', 'CH-057', (SELECT id FROM loc_ids WHERE loc_nom = 'MALINGA' AND zone_nom = 'NGOUNIE')),
  ('PLATEAU SPORTIF', 'CH-058', (SELECT id FROM loc_ids WHERE loc_nom = 'MALINGA' AND zone_nom = 'NGOUNIE')),
  ('STADE DE FOOTBALL', 'CH-059', (SELECT id FROM loc_ids WHERE loc_nom = 'MALINGA' AND zone_nom = 'NGOUNIE')),
  ('REHABILITATION PREFECTURE', 'CH-060', (SELECT id FROM loc_ids WHERE loc_nom = 'MALINGA' AND zone_nom = 'NGOUNIE')),
  ('VOIRIES DE MBIGOU (15 KM)', 'CH-061', (SELECT id FROM loc_ids WHERE loc_nom = 'MBIGOU' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION DE 06 LOGEMENTS D''ASTREINTES', 'CH-062', (SELECT id FROM loc_ids WHERE loc_nom = 'MBIGOU' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION DE 04 LOGEMENTS D''ASTREINTES', 'CH-063', (SELECT id FROM loc_ids WHERE loc_nom = 'MBIGOU' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENTS SOCIAUX (40 logements)', 'CH-064', (SELECT id FROM loc_ids WHERE loc_nom = 'MBIGOU' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION D4UN HOTEL', 'CH-065', (SELECT id FROM loc_ids WHERE loc_nom = 'MBIGOU' AND zone_nom = 'NGOUNIE')),
  ('STATION GAB''OIL', 'CH-066', (SELECT id FROM loc_ids WHERE loc_nom = 'MBIGOU' AND zone_nom = 'NGOUNIE')),
  ('TRONCON LEBAMBA-MAKONGOGNIO-MBIGOU', 'CH-067', (SELECT id FROM loc_ids WHERE loc_nom = 'LEBAMBA-MAKONGOGNIO-MBIGOU' AND zone_nom = 'NGOUNIE')),
  ('VOIRIES DE MAKONGONIO (5km)', 'CH-068', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION D''UN CENTRE DE SANTE', 'CH-069', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION D''UN BATIMENT ADMINISTRATIF', 'CH-070', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('STADE DE FOOTBALL', 'CH-071', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION DE 40 VILLAS D''ASTREINTE', 'CH-072', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('HOTEL DE MAKONGONIO', 'CH-073', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('BUREAU ADMINISTRATIF', 'CH-074', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENTS CHEFS DE VILLAGE', 'CH-075', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENT GERANT GAB OIL', 'CH-076', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('STATION SERVICE COMMUNAUTAIRE', 'CH-077', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKONGONIO' AND zone_nom = 'NGOUNIE')),
  ('COMPLEXE SCOLAIRE', 'CH-078', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('CONSTRUCTION DU CENTRE DE SANTE', 'CH-079', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('VOIRIES DE GUIETSOU (10 KM)', 'CH-080', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('PLACE DE FETE', 'CH-081', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('MARCHE', 'CH-082', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENTS DES GENDARMES', 'CH-083', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENTS DES ENSEIGNANTS', 'CH-084', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('PREFECTURE  ACTIVE', 'CH-085', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('LA MAIRIE', 'CH-086', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('LA GRANDE PREFECTURE', 'CH-087', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('LOGEMENT D''ASTREINTS (06 logements)', 'CH-088', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('STATION SERVICE', 'CH-089', (SELECT id FROM loc_ids WHERE loc_nom = 'GUIETSOU' AND zone_nom = 'NGOUNIE')),
  ('CONCEPTION ET CONSTRUCTION DE LOGEMENT', 'CH-090', (SELECT id FROM loc_ids WHERE loc_nom = 'NZENZELE' AND zone_nom = 'NGOUNIE')),
  ('CONCEPTION ET CONSTRUCTION DE LOGEMENT', 'CH-091', (SELECT id FROM loc_ids WHERE loc_nom = 'NZENZELE' AND zone_nom = 'NGOUNIE')),
  ('VOIRIES D''OKONDJA (10 km)', 'CH-092', (SELECT id FROM loc_ids WHERE loc_nom = 'OKONDJA' AND zone_nom = 'HAUT OGOOUE')),
  ('STATION GAB''OIL', 'CH-093', (SELECT id FROM loc_ids WHERE loc_nom = 'OKONDJA' AND zone_nom = 'HAUT OGOOUE')),
  ('STATION GAB''OIL', 'CH-094', (SELECT id FROM loc_ids WHERE loc_nom = 'FRANCEVILLE' AND zone_nom = 'HAUT OGOOUE')),
  ('BOUTIQUES DE FRANCEVILLE', 'CH-095', (SELECT id FROM loc_ids WHERE loc_nom = 'FRANCEVILLE' AND zone_nom = 'HAUT OGOOUE')),
  ('VOIRIES DE MAKOKOU (35 KM)', 'CH-096', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKOKOU' AND zone_nom = 'OGOOUE IVINDO')),
  ('50 LOGEMENTS DE MAKOKOU', 'CH-097', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKOKOU' AND zone_nom = 'OGOOUE IVINDO')),
  ('8 PLATEAUX SPORTIFS A MAKOKOU', 'CH-098', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKOKOU' AND zone_nom = 'OGOOUE IVINDO')),
  ('CENTRE COMMERCIAL A MAKOKOU', 'CH-099', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKOKOU' AND zone_nom = 'OGOOUE IVINDO')),
  ('DECHARGE DE MAKOKOU', 'CH-100', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKOKOU' AND zone_nom = 'OGOOUE IVINDO')),
  ('REFECTION TROTTOIR', 'CH-101', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKOKOU' AND zone_nom = 'OGOOUE IVINDO')),
  ('VOIRIES DE MEKAMBO (10 KM)', 'CH-102', (SELECT id FROM loc_ids WHERE loc_nom = 'MEKAMBO' AND zone_nom = 'OGOOUE IVINDO')),
  ('ROUTES EN TERRE MAKOKOU-MEKAMBO-EKATA (242 KM)', 'CH-103', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKOKOU-MEKAMBO-EKATA' AND zone_nom = 'OGOOUE IVINDO')),
  ('ROUTE ALEMBE - LASTOURVILLE (311 KM)
ROUTE KAZAMABIKA -CARREFOUR LEROY (45 KM)', 'CH-104', (SELECT id FROM loc_ids WHERE loc_nom = 'ALEMBE - LOPE - LASTOURVILLE' AND zone_nom = 'OGOOUE IVINDO')),
  ('STATION GAB''OIL', 'CH-105', (SELECT id FROM loc_ids WHERE loc_nom = 'MAKOKOU' AND zone_nom = 'OGOOUE IVINDO')),
  ('STATION GAB''OIL', 'CH-106', (SELECT id FROM loc_ids WHERE loc_nom = 'MEKAMBO' AND zone_nom = 'OGOOUE IVINDO')),
  ('ROUTE MBOUMBA-AKONDO (62KM)', 'CH-107', (SELECT id FROM loc_ids WHERE loc_nom = 'MBOUMA-AKONDO' AND zone_nom = 'OGOOUE MARITIME')),
  ('ROUTE MBOUMBA (20KM)', 'CH-108', (SELECT id FROM loc_ids WHERE loc_nom = 'MBOUMA' AND zone_nom = 'OGOOUE MARITIME')),
  ('RECHARGEMENT DE SABLE', 'CH-109', (SELECT id FROM loc_ids WHERE loc_nom = 'PORT GENTIL' AND zone_nom = 'OGOOUE MARITIME')),
  ('PLATEAUX MULTI SPORTS', 'CH-110', (SELECT id FROM loc_ids WHERE loc_nom = 'PORT GENTIL' AND zone_nom = 'OGOOUE MARITIME')),
  ('VOIRIE DE PORT-GENTIL (1,2 KM)', 'CH-111', (SELECT id FROM loc_ids WHERE loc_nom = 'PORT GENTIL' AND zone_nom = 'OGOOUE MARITIME')),
  ('RECHARGEMENT PLATEAU', 'CH-112', (SELECT id FROM loc_ids WHERE loc_nom = 'PORT GENTIL' AND zone_nom = 'OGOOUE MARITIME')),
  ('STATION SERVICE', 'CH-113', (SELECT id FROM loc_ids WHERE loc_nom = 'OMBOUE' AND zone_nom = 'OGOOUE MARITIME')),
  ('CONSTRUCTION D''UN STADE DE FOOTBALL ET D’UN COMPLEXE MULTISPORT
DANS LA COMMUNE DU 1ER 
ARRONDISSEMENT', 'CH-114', (SELECT id FROM loc_ids WHERE loc_nom = 'PORT GENTIL' AND zone_nom = 'OGOOUE MARITIME')),
  ('CONSTRUCTION D’UN COMPLEXE MULTISPORT  A NTCHENGUE, DANS LA COMMUNE DU 4ème ARRONDISSEMENT', 'CH-115', (SELECT id FROM loc_ids WHERE loc_nom = 'PORT GENTIL' AND zone_nom = 'OGOOUE MARITIME')),
  ('TRAVAUX DE CONSTRUCTION DE 40 LOGEMENTS DE TYPE T5 DONT 10 POUR LES 
GENDARMES DANS LA VILLE', 'CH-116', (SELECT id FROM loc_ids WHERE loc_nom = 'OMBOUE' AND zone_nom = 'OGOOUE MARITIME')),
  ('TRAVAUX DE CONSTRUCTION D’UN HANGAR DE MARCHE MODERNE', 'CH-117', (SELECT id FROM loc_ids WHERE loc_nom = 'OMBOUE' AND zone_nom = 'OGOOUE MARITIME')),
  ('VOIRIE DE LASTOURSVILLE (15 KM)', 'CH-118', (SELECT id FROM loc_ids WHERE loc_nom = 'LASTOURSVILLE' AND zone_nom = 'OGOOUE LOLO')),
  ('VOIRIE DE KOULAMOUTOU (10 KM)', 'CH-119', (SELECT id FROM loc_ids WHERE loc_nom = 'KOULAMOUTOU' AND zone_nom = 'OGOOUE LOLO'));

-- Terminé.


